# Generated by Django 4.1.1 on 2022-09-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=200)),
                ('province_image', models.ImageField(null=True, upload_to='database_images/')),
                ('province_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('testimmonial', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=200)),
                ('destination_image', models.ImageField(null=True, upload_to='database_images/')),
                ('destination_description', models.TextField()),
                ('province_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='explore_pakistan.provincess')),
            ],
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_num', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('departure_date', models.DateField(max_length=200)),
                ('arrival_date', models.DateField(max_length=200)),
                ('destination_booking', models.CharField(max_length=500, null=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='explore_pakistan.destinations')),
            ],
        ),
    ]
